### ISSUE TITLE
ctrl/stop is never called and even when it is, and returns a value, ctrl/start never receives it in prev-state?

### ISSUE THREAD

**Issue by xlfe** [keechma/keechma-next#18]

**Comment by xlfe** [comment]
So #19 seems to fix ctrl/stop being called, but I still am unable to get anything on prev-state in ctrl/start

**Comment by retro** [comment]
This should be fixed in ba81de9e03903a18928497a8a6bbdd2f0329ef50 . I'll push a new release with this fix

**Comment by retro** [comment]
Version 0.1.3 is released

**Comment by xlfe** [comment]
thanks @retro
